# Generated by Django 2.0 on 2020-11-08 04:57

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.IntegerField(unique=True, validators=[restapi.models.validate_phone])),
                ('license_number', models.CharField(max_length=200, unique=True)),
                ('car_number', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
